language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect --whitelist https://osrc.dfm.io,https://www.gitbook.io/book/gitbookio/markdown
